# Project configuration for Gaming Analysis ETL using Steam API

# Directory for output files (like the database)
output_dir: output

# Database configuration
database:
  path: output/steam_player_counts.sqlite3 # Path to the SQLite database file

# Steam API settings
steam_api:
  top_n_games: 10 # Number of top games to fetch player counts for
  # API Key should be set as an environment variable: STEAM_API_KEY
