# Project configuration for Gaming Analysis ETL

data_dir: data
output_dir: output # Added for consistency
cleaned_sessions_file: output/cleaned_sessions.csv # Updated path based on script

# Parameters for src/etl/generate_sessions.py
session_generation:
  num_users: 1000
  simulation_days: 30 # Renamed from 'days' to be more descriptive
  start_date: "2022-05-01" # Stored as string
  target_session_count: 15000
